sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.5.0
  - 2.4.0
  - 2.2.5
  - jruby-head
  - jruby-9.1.7.0
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head

before_install: gem install bundler -v 1.14.6
cache: bundler
